name: Feature Request
description: Suggest new features or improvements.
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature or improvement!

  - type: input
    id: contact
    attributes:
      label: Contact Details
      placeholder: email@example.com
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Please provide a detailed description of the feature request and its benefits.
    validations:
      required: true